language: c
dist: trusty

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - binutils-arm-none-eabi
            - gcc-arm-none-eabi
            - g++-4.9
      env: COMPILER=g++-4.9

script:
    - make